server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://nchpmwutroaeyq:8552241f495f842b0294b940501ab54a6f97cf478f6de7e5b810d35694120f90@ec2-34-195-143-54.compute-1.amazonaws.com:5432/d4opnrq69jdavf
    username: nchpmwutroaeyq
    password: 8552241f495f842b0294b940501ab54a6f97cf478f6de7e5b810d35694120f90
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Criado para o bootcamp DIO - Santander